function demo1()
{
	b1=document.getElementById('a1').value;
    localStorage.setItem('b1Local',b1);
	b2=document.getElementById('a2').value;
    localStorage.setItem('b2Local',b2);
	b3=document.getElementById('a3').value;
    localStorage.setItem('b3Local',b3);
	b4=document.getElementById('a4').value;
    localStorage.setItem('b4Local',b4);
	b5=document.getElementById('a5').value;
    localStorage.setItem('b5Local',b5);
	b6=document.getElementById('a6').value;
    localStorage.setItem('b6Local',b6);
	b7=document.getElementById('a7').value;
    localStorage.setItem('b7Local',b7);
	b8=document.getElementById('a8').value;
    localStorage.setItem('b8Local',b8);
	b9=document.getElementById('a9').value;
    localStorage.setItem('b9Local',b9);
	b10=document.getElementById('a10').value;
    localStorage.setItem('b10Local',b10);
	b11=document.getElementById('a11').value;
    localStorage.setItem('b11Local',b11);
	b12=document.getElementById('a12').value;
    localStorage.setItem('b12Local',b12);
	b13=document.getElementById('a13').value;
    localStorage.setItem('b13Local',b13);
	b14=document.getElementById('a14').value;
    localStorage.setItem('b14Local',b14);
	b15=document.getElementById('a15').value;
    localStorage.setItem('b15Local',b15);
	b16=document.getElementById('a16').value;
    localStorage.setItem('b16Local',b16);
	b17=document.getElementById('a17').value;
    localStorage.setItem('b17Local',b17);
	b18=document.getElementById('a18').value;
    localStorage.setItem('b18Local',b18);
	b19=document.getElementById('a19').value;
    localStorage.setItem('b19Local',b19);
	b20=document.getElementById('a20').value;
    localStorage.setItem('b20Local',b20);
	b21=document.getElementById('a21').value;
    localStorage.setItem('b21Local',b21);
	b22=document.getElementById('a22').value;
    localStorage.setItem('b22Local',b22);
	b23=document.getElementById('a23').value;
    localStorage.setItem('b23Local',b23);
	b24=document.getElementById('a24').value;
    localStorage.setItem('b24Local',b24);
	b25=document.getElementById('a25').value;
    localStorage.setItem('b25Local',b25);
	b26=document.getElementById('a26').value;
    localStorage.setItem('b26Local',b26);
	b27=document.getElementById('a27').value;
    localStorage.setItem('b27Local',b27);
	b28=document.getElementById('a28').value;
    localStorage.setItem('b28Local',b28);
	b29=document.getElementById('a29').value;
    localStorage.setItem('b29Local',b29);
	b30=document.getElementById('a30').value;
    localStorage.setItem('b30Local',b30);
	b31=document.getElementById('a31').value;
    localStorage.setItem('b31Local',b31);
	b32=document.getElementById('a32').value;
    localStorage.setItem('b32Local',b32);
	b33=document.getElementById('a33').value;
    localStorage.setItem('b33Local',b33);
	b34=document.getElementById('a34').value;
    localStorage.setItem('b34Local',b34);
	b35=document.getElementById('a35').value;
    localStorage.setItem('b35Local',b35);
	b36=document.getElementById('a36').value;
    localStorage.setItem('b36Local',b36);
	b37=document.getElementById('a37').value;
    localStorage.setItem('b37Local',b37);
	b38=document.getElementById('a38').value;
    localStorage.setItem('b38Local',b38);
	b39=document.getElementById('a39').value;
    localStorage.setItem('b39Local',b39);
	b40=document.getElementById('a40').value;
    localStorage.setItem('b40Local',b40);
	b41=document.getElementById('a41').value;
    localStorage.setItem('b41Local',b41);
	b42=document.getElementById('a42').value;
    localStorage.setItem('b42Local',b42);
	b43=document.getElementById('a43').value;
    localStorage.setItem('b43Local',b43);
	b44=document.getElementById('a44').value;
    localStorage.setItem('b44Local',b44);
	b45=document.getElementById('a45').value;
    localStorage.setItem('b45Local',b45);
	b46=document.getElementById('a46').value;
    localStorage.setItem('b46Local',b46);
	b47=document.getElementById('a47').value;
    localStorage.setItem('b47Local',b47);
	b48=document.getElementById('a48').value;
    localStorage.setItem('b48Local',b48);
	b49=document.getElementById('a49').value;
    localStorage.setItem('b49Local',b49);
	b50=document.getElementById('a50').value;
    localStorage.setItem('b50Local',b50);
	b51=document.getElementById('a51').value;
    localStorage.setItem('b51Local',b51);
	b52=document.getElementById('a52').value;
    localStorage.setItem('b52Local',b52);
	b53=document.getElementById('a53').value;
    localStorage.setItem('b53Local',b53);
	b54=document.getElementById('a54').value;
    localStorage.setItem('b54Local',b54);
	b55=document.getElementById('a55').value;
    localStorage.setItem('b55Local',b55);
	b56=document.getElementById('a56').value;
    localStorage.setItem('b56Local',b56);
	b57=document.getElementById('a57').value;
    localStorage.setItem('b57Local',b57);
	b58=document.getElementById('a58').value;
    localStorage.setItem('b58Local',b58);
	b59=document.getElementById('a59').value;
    localStorage.setItem('b59Local',b59);
	b60=document.getElementById('a60').value;
    localStorage.setItem('b60Local',b60);
	b61=document.getElementById('a61').value;
    localStorage.setItem('b61Local',b61);
	b62=document.getElementById('a1').value;
    localStorage.setItem('b62Local',b62);
	
	window.location.assign("file:///E:/IWT individual proj/Demo3.html")
}
function demo2()
{
	b1 = localStorage.getItem('b1Local');
	document.getElementById('c1').innerHTML=b1;
	b2 = localStorage.getItem('b2Local');
	document.getElementById('c2').innerHTML=b2;
	b3 = localStorage.getItem('b3Local');
	document.getElementById('c3').innerHTML=b3;
	b4 = localStorage.getItem('b4Local');
	document.getElementById('c4').innerHTML=b4;
	b5 = localStorage.getItem('b5Local');
	document.getElementById('c5').innerHTML=b5;
	b6 = localStorage.getItem('b6Local');
	document.getElementById('c6').innerHTML=b6;
	b7 = localStorage.getItem('b7Local');
	document.getElementById('c7').innerHTML=b7;
	b8 = localStorage.getItem('b8Local');
	document.getElementById('c8').innerHTML=b8;
	b9 = localStorage.getItem('b9Local');
	document.getElementById('c9').innerHTML=b9;
	b10 = localStorage.getItem('b10Local');
	document.getElementById('c10').innerHTML=b10;
	b11 = localStorage.getItem('b11Local');
	document.getElementById('c11').innerHTML=b11;
	b12 = localStorage.getItem('b12Local');
	document.getElementById('c12').innerHTML=b12;
	b13 = localStorage.getItem('b13Local');
	document.getElementById('c13').innerHTML=b13;
	b14 = localStorage.getItem('b14Local');
	document.getElementById('c14').innerHTML=b14;
	b15 = localStorage.getItem('b15Local');
	document.getElementById('c15').innerHTML=b15;
	b16 = localStorage.getItem('b16Local');
	document.getElementById('c16').innerHTML=b16;
	b17 = localStorage.getItem('b17Local');
	document.getElementById('c17').innerHTML=b17;
	b18 = localStorage.getItem('b18Local');
	document.getElementById('c18').innerHTML=b18;
	b19 = localStorage.getItem('b19Local');
	document.getElementById('c19').innerHTML=b19;
	b20 = localStorage.getItem('b20Local');
	document.getElementById('c20').innerHTML=b20;
	b21 = localStorage.getItem('b21Local');
	document.getElementById('c21').innerHTML=b21;
	b22 = localStorage.getItem('b22Local');
	document.getElementById('c22').innerHTML=b22;
	b23 = localStorage.getItem('b23Local');
	document.getElementById('c23').innerHTML=b23;
	b24 = localStorage.getItem('b24Local');
	document.getElementById('c24').innerHTML=b24;
	b25 = localStorage.getItem('b25Local');
	document.getElementById('c25').innerHTML=b25;
	b26 = localStorage.getItem('b26Local');
	document.getElementById('c26').innerHTML=b26;
	b27 = localStorage.getItem('b27Local');
	document.getElementById('c27').innerHTML=b27;
	b28 = localStorage.getItem('b28Local');
	document.getElementById('c28').innerHTML=b28;
	b29 = localStorage.getItem('b29Local');
	document.getElementById('c29').innerHTML=b29;
	b30 = localStorage.getItem('b30Local');
	document.getElementById('c30').innerHTML=b30;
	b31 = localStorage.getItem('b31Local');
	document.getElementById('c31').innerHTML=b31;
	b32 = localStorage.getItem('b32Local');
	document.getElementById('c32').innerHTML=b32;
	b33 = localStorage.getItem('b33Local');
	document.getElementById('c33').innerHTML=b33;
	b34 = localStorage.getItem('b34Local');
	document.getElementById('c34').innerHTML=b34;
	b35 = localStorage.getItem('b35Local');
	document.getElementById('c35').innerHTML=b35;
	b36 = localStorage.getItem('b36Local');
	document.getElementById('c36').innerHTML=b36;
	b37 = localStorage.getItem('b37Local');
	document.getElementById('c37').innerHTML=b37;
	b38 = localStorage.getItem('b38Local');
	document.getElementById('c38').innerHTML=b38;
	b39 = localStorage.getItem('b39Local');
	document.getElementById('c39').innerHTML=b39;
	b40 = localStorage.getItem('b40Local');
	document.getElementById('c40').innerHTML=b40;
	b41 = localStorage.getItem('b41Local');
	document.getElementById('c41').innerHTML=b41;
	b42 = localStorage.getItem('b42Local');
	document.getElementById('c42').innerHTML=b42;
	b43 = localStorage.getItem('b43Local');
	document.getElementById('c43').innerHTML=b43;
	b44 = localStorage.getItem('b44Local');
	document.getElementById('c44').innerHTML=b44;
	b45 = localStorage.getItem('b45Local');
	document.getElementById('c45').innerHTML=b45;
	b46 = localStorage.getItem('b46Local');
	document.getElementById('c46').innerHTML=b46;
	b47 = localStorage.getItem('b47Local');
	document.getElementById('c47').innerHTML=b47;
	b48 = localStorage.getItem('b48Local');
	document.getElementById('c48').innerHTML=b48;
	b49 = localStorage.getItem('b49Local');
	document.getElementById('c49').innerHTML=b49;
	b50 = localStorage.getItem('b50Local');
	document.getElementById('c50').innerHTML=b50;
	b51 = localStorage.getItem('b51Local');
	document.getElementById('c51').innerHTML=b51;
	b52 = localStorage.getItem('b52Local');
	document.getElementById('c52').innerHTML=b52;
	b53 = localStorage.getItem('b53Local');
	document.getElementById('c53').innerHTML=b53;
	b54 = localStorage.getItem('b54Local');
	document.getElementById('c54').innerHTML=b54;
	b55 = localStorage.getItem('b55Local');
	document.getElementById('c55').innerHTML=b55;
	b56 = localStorage.getItem('b56Local');
	document.getElementById('c56').innerHTML=b56;
	b57 = localStorage.getItem('b57Local');
	document.getElementById('c57').innerHTML=b57;
	b58 = localStorage.getItem('b58Local');
	document.getElementById('c58').innerHTML=b58;
	b59 = localStorage.getItem('b59Local');
	document.getElementById('c59').innerHTML=b59;
	b60 = localStorage.getItem('b60Local');
	document.getElementById('c60').innerHTML=b60;
	b61 = localStorage.getItem('b61Local');
	document.getElementById('c61').innerHTML=b61;
	b62 = localStorage.getItem('b62Local');
	document.getElementById('c62').innerHTML=b62;
}